openapi: 3.0.1
info:
  title: '@jupiterone/graph-sonarqube'
  description: Sonarqube integration for JupiterOne
  x-cortex-git:
    github:
      repository: JupiterOne/graph-sonarqube
  x-cortex-owners:
    - type: group
      name: JupiterOne/integrations
  x-cortex-tag: '@jupiterone/graph-sonarqube'
  x-cortex-service-groups:
    - tier-4
